### ISSUE TITLE
Is this repo still relevant for ROS2 or is there a replacement?

### ISSUE THREAD

**Issue by crdelsey** [ros/angles#15]
In ros2/ros2#520, @mikaelarguedas  removed the angles repo from the ROS2 repos list. Has this been replaced by something else?

**Comment by mikaelarguedas** [comment]
This repository is still valid and released in ROS 2 distributions https://github.com/ros2/rosdistro/blob/94f73cfc278874272fea391211f56a1c2415d474/bouncy/distribution.yaml#L153-L167

I removed it from the repos file because it is not a dependency of RViz anymore so it is not *needed* to test the packages in the `ros2.repos` file. But it is still a valuable package that can be used in ROS 2 and there are no plans to replace it with something else that I know of.

**Comment by crdelsey** [comment]
I guess I mistook *needed* to be in the global sense. :-) Thanks for clearing that up.
